<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('locations', function (Blueprint $table) {
            // Legacy ids are preserved verbatim — they are embedded in every
            // indexed URL and are the only thing the old router resolved on.
            $table->unsignedInteger('id')->primary();

            $table->string('name');
            $table->string('slug')->comment('slug(type-name)-id, generated by LegacySlug');
            $table->string('city');
            $table->string('city_slug', 100);

            $table->string('area')->nullable();
            $table->string('address')->nullable();
            $table->string('phone')->nullable();
            $table->string('email')->nullable();
            $table->string('url')->nullable();
            $table->string('facebook', 500)->nullable();
            $table->string('twitter', 500)->nullable();
            $table->string('order_url', 500)->nullable();

            $table->text('description')->nullable();
            $table->string('type')->nullable()->comment('comma-separated');
            $table->string('specific')->nullable()->comment('comma-separated');
            // Legacy column was `attributes`; renamed because that name collides
            // with Eloquent's internal $attributes property. `$SERVICES` in the
            // legacy constants.inc.php is what these actually are.
            $table->text('services')->nullable()->comment('comma-separated');

            $table->string('logo')->nullable();
            $table->string('latitude', 64)->nullable();
            $table->string('longitude', 64)->nullable();
            $table->string('hours')->nullable();

            $table->decimal('menu_price', 10, 2)->default(0);
            $table->unsignedInteger('capacity')->default(0);
            $table->decimal('rating', 10, 2)->default(0);
            $table->unsignedInteger('rating_votes')->default(0);
            $table->unsignedInteger('stars')->nullable();
            $table->unsignedInteger('views')->default(0);

            $table->string('status', 32)->default('standby');
            $table->timestamp('register_date')->nullable();
            $table->timestamps();

            $table->index('city_slug');
            $table->index('status');
            $table->index(['city_slug', 'status']);
            $table->index('slug');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('locations');
    }
};
