<?php

namespace App\Support;

/**
 * Verbatim port of the legacy site's URL::encodeUrlTerm()
 * (azilapranz.ro/lib/url.class.php:101).
 *
 * Every indexed URL on the old site was generated by that function, so this is
 * reproduced exactly rather than replaced with Str::slug() — the two disagree on
 * several inputs, and each disagreement is an indexed URL we would lose.
 *
 * Do not "clean up" the quirks below. They are load-bearing.
 */
class LegacySlug
{
    /** Characters the legacy function mapped to "-" before the catch-all regex. */
    private const PUNCTUATION = [
        ' ', '!', '?', '&', '$', '"', "'", '(', ')', '%', ':', '.', ',',
        '\\|', '+', '#', '@', ';', '/',
    ];

    /** Diacritic folding, in the same order the legacy applied it. */
    private const DIACRITICS = [
        'e' => ['é', 'ē', 'è', 'É', 'Ē', 'È'],
        'u' => ['ü', 'Ü', 'ú', 'Ú', 'ű', 'Ű'],
        'o' => ['ó', 'ö', 'Ó', 'Ö', 'ő', 'Ő'],
        'i' => ['í', 'Í'],
        'a' => ['á', 'ä', 'Á', 'Ä'],
    ];

    public static function make(?string $term): string
    {
        $term = (string) $term;

        // Util::stripEntities($term, "-")
        $term = preg_replace('/&#?[a-z0-9]{2,8};/i', '-', $term);

        foreach (self::DIACRITICS as $replacement => $search) {
            $term = str_replace($search, $replacement, $term);
        }

        $term = str_replace(self::PUNCTUATION, '-', $term);

        // Romanian diacritics were never folded by the legacy function — they fell
        // through to this catch-all and each became a "-". Preserved deliberately:
        // "Piaţa" produced "pia-a", not "piata".
        $term = preg_replace('/[^A-Za-z0-9 -]/', '-', $term);

        // Single pass, not a loop. str_replace() scans left to right without
        // re-examining what it just wrote, so long dash runs are only partially
        // collapsed (e.g. "a-----b" => "a--b"). The legacy behaved this way and
        // its URLs are indexed that way.
        $term = str_replace(['---', '--'], '-', $term);

        $term = strtolower(trim($term, '-'));

        // urlencode() is a no-op on the surviving [a-z0-9-] charset, but the
        // legacy called it, so the behaviour is identical either way.
        return $term;
    }

    /**
     * Canonical path segment for a venue: slug(type + "-" + name) + "-" + id.
     *
     * `type` is a comma-separated multi-value column, so "restaurant,pizzerie"
     * widens the slug rather than picking one value.
     */
    public static function forLocation(?string $type, string $name, int $id): string
    {
        return self::make($type.'-'.$name).'-'.$id;
    }
}
